meta_data:
  name: store-example
  description: This is an example of how to use the store action
  version: 1.0.0
  author: Andrew Pye
  contact:
  create_date: "2022-11-13 11:39:44"
  update_date: "2022-11-13 11:39:44"
jobs:
  - key: store-example
    actions:
      - action: store
        config:
          bucket: "my_data"
          key: "name"
          value: "Andrew"
      - action: "print;{{get_store `my_data` `name`}}"
      
parameters:
  
