---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.22.60.120-10.22.60.130
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: mpc
  namespace: metallb-system